---

- hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:
    - name: group | create group
      group:
        name: jim

    - name: user | create users
      user:
        name: jim
        groups: sudo
        append: yes
        state: present
        createhome: yes
        shell: /bin/bash
        password: "{{ my_password }}"

    - name: authorized_key | Deploy authorized_key
      authorized_key:
        user: jim
        key: "{{ item }}"
      loop: "{{ authorized_keys }}"

